name: oxlint ecosystem ci

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:
    inputs: # for create comment action https://github.com/peter-evans/create-or-update-comment?tab=readme-ov-file#action-inputs
      issue-number:
        required: false
        type: string
      comment-id:
        required: false
        type: string
      ref:
        required: false
        type: string
        default: 'main'

defaults:
  run:
    shell: bash

jobs:
  reply:
    name: Reply
    if: ${{ inputs.issue-number && inputs.comment-id }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.PAT }}
          repository: oxc-project/oxc
          issue-number: ${{ inputs.issue-number }}
          comment-id: ${{ inputs.comment-id }}
          reactions: eyes

  build:
    name: Build
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout oxc (${{ inputs.ref }})
        uses: actions/checkout@v4
        with:
          repository: oxc-project/oxc
          ref: ${{ inputs.ref }}

      - name: Install Rust
        uses: Boshen/setup-rust@main
        with:
          save-cache: ${{ github.ref_name == 'main' }}

      - name: Build oxlint
        run: cargo oxlint

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: oxlint
          path: ./target/release/oxlint

  checkout:
    name: Read matrix.json
    needs: build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setmatrix.outputs.content }}
    steps:
      - uses: taiki-e/checkout-action@v1

      - id: setmatrix
        uses: jaywcjlove/github-action-read-file@main
        with:
          localfile: ./matrix.json

  test:
    needs: checkout
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.checkout.outputs.matrix) }}
    name: Test ${{ matrix.repository }}
    steps:
      - name: Clone ${{ matrix.repository }}
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repository }}
          ref: ${{ matrix.ref }}
          path: ${{ matrix.path }}

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: oxlint
          path: ${{ matrix.path }}

      - name: chmod +x oxlint
        run: chmod +x ./oxlint
        working-directory: ${{ matrix.path }}

      - name: Run
        working-directory: ${{ matrix.path }}
        run: ${{ matrix.command }}

      - name: Check Panic
        working-directory: ${{ matrix.path }}
        # NOTE (@DonIsaac): should we enable import-plugin?
        # NOTE (@DonIsaac): should we test nursery rules too?
        run: |
          set +e # disable exit on run

          ./oxlint \
            --fix \
            --jsdoc-plugin \
            --jest-plugin \
            --vitest-plugin \
            --jsx-a11y-plugin \
            --nextjs-plugin \
            --react-perf-plugin \
            -D all \
            --silent

          EXIT_CODE=$?

          # Panic returns exit code > 1, e.g. 101 when a Rust program panics
          if [ $EXIT_CODE -gt 1 ]; then
              echo "exitcode=$EXIT_CODE" >> $GITHUB_OUTPUT
              exit $EXIT_CODE
          fi

          echo "exitcode=0" >> $GITHUB_OUTPUT
          exit 0

      # Check for invalid syntax after lint rule violations have been fixed.
      # All lint rules are set to `warning` here, so an exit code > 0 is either
      # a parse error or a panic.
      - name: Re-Parse After `--fix`
        working-directory: ${{ matrix.path }}
        if: ${{ matrix.path != 'DefinitelyTyped' }}
        run: |
          oxlint_args="\
            --jsdoc-plugin \
            --jest-plugin \
            --vitest-plugin \
            --jsx-a11y-plugin \
            --nextjs-plugin \
            --react-perf-plugin \
            -A all \
          "

          has_oxlintignore=$(ls | grep .oxlintignore | wc -l | xargs)
          if [[ $has_oxlintignore -gt 0 ]]; then
            oxlint_args="$oxlint_args --ignore-path .oxlintignore"
          fi

          ./oxlint $oxlint_args

  comment:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Reply Comment
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/github-script@v7
        id: script
        if: ${{ inputs.issue-number }}
        with:
          github-token: ${{ secrets.PAT }}
          result-encoding: string
          script: |
            const {
              data: { jobs },
            } = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
              per_page: 100,
            });
            let result = jobs
              .filter((job) => job.name.startsWith("Test "))
              .map((job) => {
                const suite = job.name.slice(5);
                return { suite, conclusion: job.conclusion, link: job.html_url };
              });
            const url = `${context.serverUrl}//${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            const urlLink = `[Open](${url})`;
            const conclusionEmoji = {
              success: ":white_check_mark:",
              failure: ":x:",
              cancelled: ":stop_button:",
            };
            const body = `
            ## [Oxlint Ecosystem CI](${urlLink})
            | suite | result |
            |-------|--------|
            ${result.map((r) => `| [${r.suite}](${r.link}) | ${conclusionEmoji[r.conclusion]} |`).join("\n")}
            `;
            return body;

      - uses: peter-evans/create-or-update-comment@v4
        if: ${{ inputs.issue-number && inputs.comment-id }}
        with:
          token: ${{ secrets.PAT }}
          repository: oxc-project/oxc
          issue-number: ${{ inputs.issue-number }}
          comment-id: ${{ inputs.comment-id }}
          body: ${{ steps.script.outputs.result }}
          edit-mode: replace
